;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_memcpy
	.import		_cr_init
	.import		_cr_register
	.export		_cs_init
	.export		_cs_place

; ---------------------------------------------------------------
; void __near__ cs_init (__near__ struct COMBOSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_cs_init: near

.segment	"GAME_CODE"

	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$4C
	sta     (ptr1)
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$01
	sta     (ptr1),y
	ina
	sta     (sp),y
L0123:	sta     (sp)
	cmp     #$10
	bcs     L010B
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	asl     a
	ina
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	asl     a
	asl     a
	clc
	adc     #$02
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	asl     a
	asl     a
	clc
	adc     #$03
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0123
L010B:	lda     #$00
L0124:	sta     (sp)
	cmp     #$10
	jcs     L010E
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	and     #$03
	sta     ptr1
	lda     (sp),y
	and     #$0C
	asl     a
	asl     a
	clc
	adc     ptr1
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	and     #$03
	sta     ptr1
	lda     (sp),y
	and     #$0C
	asl     a
	asl     a
	clc
	adc     ptr1
	clc
	adc     #$04
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	and     #$03
	sta     ptr1
	lda     (sp),y
	and     #$0C
	asl     a
	asl     a
	clc
	adc     ptr1
	clc
	adc     #$08
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	and     #$03
	sta     ptr1
	lda     (sp),y
	ldx     #$00
	and     #$0C
	jsr     shlax2
	clc
	adc     ptr1
	bcc     L0108
	inx
L0108:	ldy     #$0C
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	jmp     L0124
L010E:	lda     #$00
L0125:	sta     (sp)
	cmp     #$10
	bcs     L0111
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$20
	jsr     incaxy
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	ldy     #$30
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0125
L0111:	lda     #$00
L0126:	sta     (sp)
	cmp     #$04
	bcs     L0114
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     #$05
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     shlax4
	ldy     #$0A
	jsr     incaxy
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     shlax4
	ldy     #$0F
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0126
L0114:	lda     #$00
L0127:	sta     (sp)
	cmp     #$04
	bcs     L0117
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     #$03
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	asl     a
	asl     a
	asl     a
	asl     a
	clc
	adc     #$06
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     shlax4
	ldy     #$09
	jsr     incaxy
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     shlax4
	ldy     #$0C
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0127
L0117:	lda     #$00
L0128:	sta     (sp)
	cmp     #$04
	bcs     L011A
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ldy     #$14
	jsr     incaxy
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$28
	jsr     incaxy
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	ldy     #$3C
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0128
L011A:	lda     #$00
L0129:	sta     (sp)
	cmp     #$04
	bcs     L011D
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$0C
	jsr     incaxy
	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ldy     #$18
	jsr     incaxy
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$24
	jsr     incaxy
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	ldy     #$30
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L0129
L011D:	lda     #$00
L012A:	sta     (sp)
	cmp     #$04
	bcs     L0120
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$10
	jsr     incaxy
	ina
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$20
	jsr     incaxy
	clc
	adc     #$02
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$30
	jsr     incaxy
	clc
	adc     #$03
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L012A
L0120:	lda     #$00
L012B:	sta     (sp)
	cmp     #$04
	bcs     L0093
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	asl     a
	asl     a
	clc
	adc     #$03
	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$10
	jsr     incaxy
	clc
	adc     #$02
	jsr     pusha
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$20
	jsr     incaxy
	ina
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	jsr     shlax2
	ldy     #$30
	jsr     incaxy
	jsr     pusha
	jsr     _cr_init
	lda     (sp)
	ina
	bra     L012B
L0093:	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	lda     #$00
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #$2A
	jsr     pusha
	lda     #$3F
	jsr     pusha
	jsr     _cr_init
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$16
	jsr     pusha
	lda     #$29
	jsr     pusha
	lda     #$3C
	jsr     pusha
	jsr     _cr_init
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	lda     #$0C
	jsr     pusha
	lda     #$19
	jsr     pusha
	lda     #$26
	jsr     pusha
	lda     #$33
	jsr     pusha
	jsr     _cr_init
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	lda     #$0F
	jsr     pusha
	lda     #$1A
	jsr     pusha
	lda     #$25
	jsr     pusha
	lda     #$30
	jsr     pusha
	jsr     _cr_init
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ cs_place (__near__ struct COMBOSET_S*, int, signed char)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_cs_place: near

.segment	"GAME_CODE"

	jsr     decsp1
	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaidx
	tax
	bmi     L00CD
	ldx     #$00
	tya
	jmp     incsp6
L00CD:	lda     #$00
L012F:	sta     (sp)
	ldx     #$00
	lda     (sp)
	bpl     L00D7
	dex
L00D7:	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$00
	jsr     ldaidx
	jsr     tosicmp
	jpl     L00D1
	ldy     #$05
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	bpl     L00DE
	dex
L00DE:	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	jsr     _cr_register
	stx     tmp1
	ora     tmp1
	jeq     L00D2
	ldy     #$05
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	bpl     L00E5
	dex
L00E5:	jsr     mulax9
	jsr     tosaddax
	ldy     #$02
	jsr     ldaidx
	cmp     #$04
	bne     L00E1
	ldy     #$05
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	bpl     L00E9
	dex
L00E9:	jsr     mulax9
	jsr     tosaddax
	jsr     ldaxi
	ldy     #$02
	cmp     (sp),y
	bne     L00E1
	txa
	iny
	cmp     (sp),y
	bne     L00E1
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	ldy     #$01
	sta     (ptr1),y
	jmp     L00D2
L00E1:	ldy     #$05
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	bpl     L00F2
	dex
L00F2:	jsr     mulax9
	jsr     tosaddax
	ldy     #$04
	jsr     ldaxidx
	stx     tmp1
	ora     tmp1
	bne     L00D2
	tax
	lda     (sp)
	bpl     L00F5
	dex
L00F5:	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$00
	jsr     ldaidx
	jsr     decax1
	jsr     tosicmp
	beq     L00F3
	ldy     #$05
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	bpl     L00F9
	dex
L00F9:	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     incax2
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	ldy     #$00
	jsr     ldaidx
	jsr     decax1
	jsr     mulax9
	jsr     tosaddax
	jsr     pushax
	jsr     _cs_swap
	lda     (sp)
	dea
	sta     (sp)
L00F3:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$00
	jsr     ldaidx
	dea
	jsr     staspidx
L00D2:	lda     (sp)
	ina
	jmp     L012F
L00D1:	ldy     #$05
	jsr     ldaxysp
	ldy     #$01
	jsr     ldaidx
	tax
	bmi     L0101
	ldx     #$00
	tya
	jmp     incsp6
L0101:	ldx     #$00
	txa
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ cs_swap (__near__ struct COMBOROW_S*, __near__ struct COMBOROW_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_cs_swap: near

.segment	"GAME_CODE"

	ldy     #$09
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$10
	jsr     pushwysp
	ldx     #$00
	lda     #$09
	jsr     _memcpy
	ldy     #$0E
	jsr     pushwysp
	ldy     #$0E
	jsr     pushwysp
	ldx     #$00
	lda     #$09
	jsr     _memcpy
	ldy     #$0A
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$08
L00CB:	lda     (sp),y
	sta     (ptr1),y
	dey
	bpl     L00CB
	ldy     #$0D
	jmp     addysp

.endproc

