;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_clock
	.import		_memcpy
	.import		_memset
	.export		_vs_clear
	.export		_vs_set
	.export		_vs_isempty
	.export		_vs_incscore
	.export		_vs_decscore
	.export		_vs_isable
	.export		_vs_addscore
	.export		_vs_subscore
	.export		_vs_disable
	.export		_vs_pickmember
	.export		_vs_add
	.export		_vs_sub
	.export		_vs_combine
	.export		_vs_numactive

; ---------------------------------------------------------------
; void __near__ vs_clear (__near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_clear: near

.segment	"GAME_CODE"

	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
L0128:	sta     (ptr1),y
	iny
	cpy     #$82
	bne     L0128
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ vs_set (__near__ struct VSET_S*, __near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_set: near

.segment	"GAME_CODE"

	ldy     #$05
	jsr     pushwysp
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	lda     #$82
	jsr     _memcpy
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ vs_isempty (__near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_isempty: near

.segment	"GAME_CODE"

	jsr     ldax0sp
	jsr     ldaxi
	cpx     #$00
	bne     L0017
	cmp     #$00
	bne     L0129
	ina
	jmp     incsp2
L0017:	ldx     #$00
L0129:	txa
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ vs_incscore (__near__ struct VSET_S*, signed char)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_incscore: near

.segment	"GAME_CODE"

	ldy     #$04
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha0
	jsr     _vs_addscore
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ vs_decscore (__near__ struct VSET_S*, signed char)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_decscore: near

.segment	"GAME_CODE"

	ldy     #$04
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     #$01
	jsr     pusha0
	jsr     _vs_subscore
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; int __near__ vs_isable (__near__ struct VSET_S*, signed char)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_isable: near

.segment	"GAME_CODE"

	lda     (sp)
	asl     a
	bcs     L012B
	lda     (sp)
	sec
	sbc     #$40
	bvs     L0023
	eor     #$80
L0023:	bpl     L001C
L012B:	ldx     #$00
	bra     L012A
L001C:	ldy     #$02
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	bpl     L0029
	dex
L0029:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cmp     #$01
	txa
	sbc     #$00
	bvs     L002A
	eor     #$80
L002A:	asl     a
	lda     #$00
	tax
	bcc     L001B
	ina
	jmp     incsp3
L012A:	txa
L001B:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ vs_addscore (__near__ struct VSET_S*, signed char, int)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_addscore: near

.segment	"GAME_CODE"

	ldy     #$02
	lda     (sp),y
	asl     a
	bcc     L012D
	jmp     incsp5
L012D:	lda     (sp),y
	sec
	sbc     #$40
	bvs     L0037
	eor     #$80
L0037:	bpl     L012E
	jmp     incsp5
L012E:	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L003C
	dex
L003C:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	bne     L0039
	cmp     #$00
	bne     L0039
	ldy     #$04
	jsr     ldaxysp
	jsr     pushax
	jsr     ldaxi
	ina
	bne     L003F
	inx
L003F:	ldy     #$00
	jsr     staxspidx
L0039:	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L0042
	dex
L0042:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushax
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	ldy     #$00
	jsr     staxspidx
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ vs_subscore (__near__ struct VSET_S*, signed char, int)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_subscore: near

.segment	"GAME_CODE"

	ldy     #$02
	lda     (sp),y
	asl     a
	bcc     L0131
	jmp     incsp5
L0131:	lda     (sp),y
	sec
	sbc     #$40
	bvs     L0051
	eor     #$80
L0051:	bpl     L0132
	jmp     incsp5
L0132:	lda     (sp)
	dey
	ora     (sp),y
	bne     L0133
	jmp     incsp5
L0133:	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L0058
	dex
L0058:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cmp     (sp)
	txa
	ldy     #$01
	sbc     (sp),y
	bvs     L012F
	eor     #$80
L012F:	bpl     L005D
	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L005B
	dex
L005B:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushax
	jsr     ldaxi
	sec
	ldy     #$02
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$00
	jsr     staxspidx
	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	bpl     L0060
	dex
L0060:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	bne     L005D
	cmp     #$00
	bne     L005D
	ldy     #$04
	jsr     ldaxysp
	jsr     pushax
	jsr     ldaxi
	jsr     decax1
	ldy     #$00
	jsr     staxspidx
L005D:	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ vs_disable (__near__ struct VSET_S*, signed char)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_disable: near

.segment	"GAME_CODE"

	lda     (sp)
	asl     a
	bcs     L0068
	lda     (sp)
	sec
	sbc     #$40
	bvs     L0070
	eor     #$80
L0070:	bmi     L0068
	ldy     #$02
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	bpl     L0075
	dex
L0075:	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	bne     L0135
	cmp     #$00
	beq     L0072
L0135:	ldy     #$02
	jsr     ldaxysp
	jsr     pushax
	jsr     ldaxi
	jsr     decax1
	ldy     #$00
	jsr     staxspidx
L0072:	ldy     #$02
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	bpl     L007A
	dex
L007A:	jsr     aslax1
	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
L0068:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; signed char __near__ vs_pickmember (__near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_pickmember: near

.segment	"GAME_CODE"

	jsr     decsp5
	ldy     #$06
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	ldy     #$03
	jsr     staxysp
	lda     #$00
L0147:	sta     (sp)
	cmp     #$40
	bcs     L0142
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L013C
	inx
	clc
L013C:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	ldy     #$06
	jsr     ldaxysp
	jsr     tosicmp
	bmi     L0082
	beq     L0082
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L013D
	inx
	clc
L013D:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	ldy     #$03
	jsr     staxysp
L0082:	lda     (sp)
	ina
	bra     L0147
L0142:	lda     #$00
L0148:	sta     (sp)
	cmp     #$40
	bcs     L0090
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L013E
	inx
	clc
L013E:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	ldy     #$03
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bvc     L013A
	eor     #$80
L013A:	bpl     L0091
	ldy     #$08
	jsr     pushwysp
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	jsr     _vs_disable
L0091:	lda     (sp)
	ina
	bra     L0148
L0090:	jsr     _clock
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	jsr     ldaxi
	jsr     tosumodax
	ldy     #$01
	sta     (sp),y
	lda     #$00
	iny
	sta     (sp),y
L0149:	sta     (sp)
	cmp     #$40
	bcs     L00A4
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L013F
	inx
	clc
L013F:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cmp     #$01
	txa
	sbc     #$00
	bvs     L00AF
	eor     #$80
L00AF:	bpl     L00A5
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	dey
	cmp     (sp),y
	bne     L00A5
	lda     (sp)
	bpl     L007C
	dex
	jmp     incsp7
L00A5:	lda     (sp)
	ina
	bra     L0149
L00A4:	ldx     #$FF
	txa
L007C:	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ vs_add (__near__ struct VSET_S*, __near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_add: near

.segment	"GAME_CODE"

	jsr     decsp1
	lda     #$00
L0150:	sta     (sp)
	cmp     #$40
	bcs     L00B7
	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L014C
	inx
	clc
L014C:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushax
	jsr     ldaxi
	sta     sreg
	stx     sreg+1
	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	asl     a
	bcc     L014D
	inx
	clc
L014D:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	ldy     #$00
	jsr     staxspidx
	lda     (sp)
	ina
	bra     L0150
L00B7:	ldy     #$06
	jsr     pushwysp
	ldy     #$08
	jsr     pushwysp
	jsr     _vs_numactive
	ldy     #$00
	jsr     staxspidx
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ vs_sub (__near__ struct VSET_S*, __near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_sub: near

.segment	"GAME_CODE"

	jsr     decsp1
	lda     #$00
L015F:	sta     (sp)
	cmp     #$40
	jcs     L00C8
	ldy     #$02
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0156
	inx
	clc
L0156:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	asl     a
	bcc     L0157
	inx
	clc
L0157:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jsr     tosicmp
	bmi     L00D0
	beq     L00D0
	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0158
	inx
	clc
L0158:	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
	bra     L015E
L00D0:	ldy     #$04
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0159
	inx
	clc
L0159:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushax
	jsr     pushw
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$04
	lda     (sp),y
	asl     a
	bcc     L015A
	inx
	clc
L015A:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jsr     tossubax
	ldy     #$00
	jsr     staxspidx
L015E:	lda     (sp)
	ina
	jmp     L015F
L00C8:	ldy     #$06
	jsr     pushwysp
	ldy     #$08
	jsr     pushwysp
	jsr     _vs_numactive
	ldy     #$00
	jsr     staxspidx
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ vs_combine (__near__ struct VSET_S*, __near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_combine: near

.segment	"GAME_CODE"

	ldy     #$85
	jsr     subysp
	ldy     #$86
	jsr     ldaxysp
	jsr     ldaxi
	cmp     #$01
	txa
	sbc     #$00
	bvc     L00E2
	eor     #$80
L00E2:	jmi     L0111
	ldy     #$86
	jsr     ldaxysp
	jsr     ldaxi
	cmp     #$40
	txa
	sbc     #$00
	bvs     L00E6
	eor     #$80
L00E6:	jmi     L0111
	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	jsr     _vs_clear
	ldx     #$00
	txa
	ldy     #$01
	jsr     staxysp
L016F:	sta     (sp)
	cmp     #$40
	bcs     L00EC
	ldy     #$88
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0166
	inx
	clc
L0166:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	ldy     #$04
	jsr     ldaxysp
	jsr     tosicmp
	bmi     L00ED
	beq     L00ED
	ldy     #$88
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0167
	inx
	clc
L0167:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	ldy     #$01
	jsr     staxysp
L00ED:	lda     (sp)
	ina
	bra     L016F
L00EC:	ldy     #$01
	lda     (sp),y
	iny
	ora     (sp),y
	jeq     L0111
	lda     #$00
L0170:	sta     (sp)
	cmp     #$40
	bcs     L00FE
	ldy     #$88
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0168
	inx
	clc
L0168:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	ldy     #$01
	cmp     (sp),y
	bne     L00FF
	txa
	iny
	cmp     (sp),y
	bne     L00FF
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0169
	inx
	clc
L0169:	adc     #$05
	bcc     L010B
	inx
	clc
L010B:	adc     sp
	sta     sreg
	txa
	adc     sp+1
	sta     sreg+1
	ldy     #$86
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L016A
	inx
	clc
L016A:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	sta     (sreg)
	ldy     #$01
	txa
	sta     (sreg),y
L00FF:	lda     (sp)
	ina
	bra     L0170
L00FE:	lda     #$03
	jsr     leaa0sp
	jsr     pushax
	jsr     _vs_numactive
	ldy     #$03
	jsr     staxysp
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0113
	eor     #$80
L0113:	bpl     L0111
	ldy     #$8A
	jsr     pushwysp
	lda     #$05
	jsr     leaa0sp
	jsr     pushax
	jsr     _vs_set
L0111:	ldy     #$89
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; int __near__ vs_numactive (__near__ struct VSET_S*)
; ---------------------------------------------------------------

.segment	"GAME_CODE"

.proc	_vs_numactive: near

.segment	"GAME_CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
L0175:	sta     (sp)
	cmp     #$40
	bcs     L011A
	ldy     #$03
	jsr     ldaxysp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0172
	inx
	clc
L0172:	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cmp     #$01
	txa
	sbc     #$00
	bvs     L0125
	eor     #$80
L0125:	bpl     L011B
	ldy     #$01
	lda     (sp),y
	ina
	sta     (sp),y
L011B:	lda     (sp)
	ina
	bra     L0175
L011A:	ldy     #$01
	lda     (sp),y
	ldx     #$00
	jmp     incsp4

.endproc

