;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_lynx_load
	.import		_strcmp
	.import		_strcpy
	.import		_kbhit
	.import		_cgetc
	.import		_tgi_setpalette
	.import		_tgi_getpalette
	.import		_tgi_ioctl
	.import		_joy_read
	.import		_LynxSD_OpenFile
	.import		_LynxSD_ReadFile
	.import		_LynxSD_WriteFile
	.import		_LynxSD_CloseFile
	.import		_LynxSD_OpenFileTimeout
	.export		_SDCheck
	.export		_saveBuf
	.export		_SDSavePath
	.export		_saveptr
	.export		_halted
	.export		_reset
	.export		_musicEnabled
	.export		_altview
	.export		_lastmove
	.export		_ingame
	.export		_flipflop
	.export		_tunenum
	.export		_menutune
	.import		_lnx_eeprom_read
	.import		_lnx_eeprom_write
	.import		_lynx_snd_pause
	.import		_lynx_snd_continue
	.import		_lynx_snd_play
	.import		_lynx_snd_stop
	.import		_playPCMSample
	.import		_stopPCMSample
	.import		_openn
	.import		_musicptr
	.import		_intro
	.import		_menu
	.import		_selectLevel
	.import		_selectGame
	.import		_select2PMode
	.import		_game
	.import		_game2P
	.import		_netgame
	.import		_showHistory
	.import		_showHistory2P
	.import		_stats
	.import		_options
	.import		_askPlayAgain
	.import		_credits
	.import		_tutorial
	.import		_INTRO_FILENR
	.import		_MENU_FILENR
	.import		_CREDITS_FILENR
	.import		_GAME_FILENR
	.import		_GAME2P_FILENR
	.import		_TUNE0_FILENR
	.import		_TUNE1_FILENR
	.import		_TUNE2_FILENR
	.import		_TUNE3_FILENR
	.export		_backupPal
	.export		_grayPal
	.export		_eewrite
	.export		_writeSaveData
	.export		_readSaveData
	.export		_resetSaveData
	.export		_play_Tune
	.export		_addGame
	.export		_main
	.export		_checkInput
	.export		_play_PCM

.segment	"DATA"

_SDCheck:
	.byte	$FF
_halted:
	.byte	$00
_reset:
	.byte	$00
_musicEnabled:
	.byte	$01
_altview:
	.byte	$01
_lastmove:
	.byte	$01
_ingame:
	.byte	$00
_flipflop:
	.byte	$00
_tunenum:
	.byte	$02
_menutune:
	.byte	$00

.segment	"RODATA"

_SDSavePath:
	.byte	$2F,$73,$61,$76,$65,$73,$2F,$34,$74,$74,$75,$64,$65,$2E,$73,$61
	.byte	$76,$00
L0109:
	.byte	$54,$54,$54,$54,$00
L0090	:=	L0109+0

.segment	"BSS"

_saveBuf:
	.res	128,$00
_saveptr:
	.res	2,$00
_backupPal:
	.res	32,$00
_grayPal:
	.res	32,$00

; ---------------------------------------------------------------
; void __near__ eewrite (unsigned char, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_eewrite: near

.segment	"CODE"

	jsr     decsp2
	ldy     #$04
	lda     (sp),y
	jsr     _lnx_eeprom_read
	jsr     stax0sp
	ldy     #$02
	cmp     (sp),y
	bne     L02BD
	txa
	iny
	cmp     (sp),y
	beq     L002E
L02BD:	ldy     #$04
	lda     (sp),y
	jsr     pusha
	ldy     #$04
	jsr     ldaxysp
	jsr     _lnx_eeprom_write
L002E:	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ writeSaveData (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_writeSaveData: near

.segment	"CODE"

	jsr     decsp1
	lda     _SDCheck
	cmp     #$01
	bne     L0034
	lda     #<(_SDSavePath)
	ldx     #>(_SDSavePath)
	jsr     _LynxSD_OpenFile
	cpx     #$00
	bne     L0044
	cmp     #$00
	bne     L0044
	lda     #<(_saveBuf)
	ldx     #>(_saveBuf)
	jsr     pushax
	ldx     #$00
	lda     #$80
	jsr     _LynxSD_WriteFile
	ldy     #$00
	jsr     _LynxSD_CloseFile
	jmp     incsp1
L0034:	lda     _SDCheck
	bne     L0044
L02C2:	sta     (sp)
	cmp     #$40
	bcs     L0044
	lda     (sp)
	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L02BF
	inx
	clc
L02BF:	adc     #<(_saveBuf)
	tay
	txa
	adc     #>(_saveBuf)
	tax
	tya
	jsr     pushw
	jsr     _eewrite
	lda     (sp)
	ina
	bra     L02C2
L0044:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ readSaveData (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_readSaveData: near

.segment	"CODE"

	jsr     decsp3
	lda     _SDCheck
	cmp     #$FF
	bne     L0061
	lda     #<(_SDSavePath)
	ldx     #>(_SDSavePath)
	jsr     _LynxSD_OpenFileTimeout
	jsr     stax0sp
	cpx     #$00
	bne     L0056
	cmp     #$00
	bne     L0056
	lda     #$02
	bra     L02C4
L0056:	ldy     #$01
	lda     (sp),y
	bne     L005C
	lda     (sp)
	cmp     #$01
	bne     L005C
	dea
	bra     L02C4
L005C:	lda     #$FE
L02C4:	sta     _SDCheck
L0061:	lda     _SDCheck
	bne     L0064
	ldy     #$02
L02C9:	sta     (sp),y
	cmp     #$40
	bcs     L0083
	ldx     #$00
	lda     (sp),y
	asl     a
	bcc     L02C6
	inx
	clc
L02C6:	adc     #<(_saveBuf)
	tay
	txa
	adc     #>(_saveBuf)
	tax
	tya
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     _lnx_eeprom_read
	ldy     #$00
	jsr     staxspidx
	ldy     #$02
	lda     (sp),y
	ina
	bra     L02C9
L0064:	lda     _SDCheck
	sec
	sbc     #$01
	bvs     L0077
	eor     #$80
L0077:	bpl     L0083
	lda     _SDCheck
	cmp     #$01
	bne     L0078
	lda     #<(_SDSavePath)
	ldx     #>(_SDSavePath)
	jsr     _LynxSD_OpenFile
	cpx     #$00
	bne     L0083
	cmp     #$00
	bne     L0083
	bra     L02D0
L0078:	lda     #$01
	sta     _SDCheck
L02D0:	lda     #<(_saveBuf)
	ldx     #>(_saveBuf)
	jsr     pushax
	ldx     #$00
	lda     #$80
	jsr     _LynxSD_ReadFile
	ldy     #$00
	jsr     _LynxSD_CloseFile
L0083:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ resetSaveData (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_resetSaveData: near

.segment	"CODE"

	jsr     decsp2
	stz     _saveBuf+4
	stz     _saveBuf+4+1
	lda     #<(_saveBuf)
	ldx     #>(_saveBuf)
	jsr     pushax
	lda     #<(L0090)
	ldx     #>(L0090)
	jsr     _strcpy
	ldx     #$00
	lda     _musicEnabled
	ora     #$06
	sta     _saveBuf+6
	stz     _saveBuf+6+1
	lda     #$04
L02D2:	jsr     stax0sp
	cmp     #$40
	txa
	sbc     #$00
	bvc     L009C
	eor     #$80
L009C:	bpl     L0096
	jsr     ldax0sp
	jsr     aslax1
	clc
	adc     #<(_saveBuf)
	sta     ptr1
	txa
	adc     #>(_saveBuf)
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
	jsr     ldax0sp
	ina
	bne     L02D2
	inx
	bra     L02D2
L0096:	jsr     _writeSaveData
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ play_Tune (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_play_Tune: near

.segment	"CODE"

	lda     _ingame
	beq     L00A4
	stz     _menutune
	ldx     #$00
	lda     _tunenum
	ina
	bne     L00AB
	inx
L00AB:	jsr     pushax
	lda     #$03
	jsr     tosumoda0
	sta     _tunenum
	lda     _tunenum
	bne     L02D4
	lda     #<(_TUNE1_FILENR)
	ldx     #>(_TUNE1_FILENR)
	bra     L02D3
L02D4:	lda     _tunenum
	cmp     #$01
	bne     L02D5
	lda     #<(_TUNE2_FILENR)
	ldx     #>(_TUNE2_FILENR)
L02D3:	jsr     _lynx_load
L02D5:	lda     _tunenum
	cmp     #$02
	bne     L00B5
	lda     #<(_TUNE3_FILENR)
	ldx     #>(_TUNE3_FILENR)
	jsr     _lynx_load
L00B5:	lda     _musicEnabled
	beq     L00CB
	lda     #$00
	jsr     pusha
	lda     _musicptr
	ldx     _musicptr+1
	jsr     _lynx_snd_play
	lda     #$01
	jsr     pusha
	lda     _musicptr+2
	ldx     _musicptr+2+1
	jsr     _lynx_snd_play
	lda     #$02
	jsr     pusha
	lda     _musicptr+4
	ldx     _musicptr+4+1
	jmp     _lynx_snd_play
L00A4:	lda     _menutune
	bne     L00CB
	lda     #<(_TUNE0_FILENR)
	ldx     #>(_TUNE0_FILENR)
	jsr     _lynx_load
	lda     #$01
	sta     _menutune
	lda     _musicEnabled
	beq     L00CB
	lda     #$00
	jsr     pusha
	lda     _musicptr
	ldx     _musicptr+1
	jsr     _lynx_snd_play
	lda     #$01
	jsr     pusha
	lda     _musicptr+2
	ldx     _musicptr+2+1
	jsr     _lynx_snd_play
	lda     #$02
	jsr     pusha
	lda     _musicptr+4
	ldx     _musicptr+4+1
	jmp     _lynx_snd_play
L00CB:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ addGame (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_addGame: near

.segment	"CODE"

	jsr     decsp2
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$01
	sta     (sp),y
	cmp     #$FF
	bcs     L00DB
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	jsr     pushax
	ldy     #$03
	clc
	lda     #$01
	adc     (sp),y
	sta     (sp),y
	ldy     #$00
	jsr     staspidx
L00DB:	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	dey
	lda     (sp),y
	cmp     #$27
	bcs     L02D7
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	ldy     #$09
	jsr     incaxy
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     tosaddax
	jmp     L02E0
L02D7:	lda     #$00
L02DB:	sta     (sp)
	cmp     #$25
	bcs     L00ED
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$0A
	jsr     incaxy
	jsr     pushax
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     tosaddax
	jsr     tosaddax
	jsr     pushax
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$0A
	jsr     incaxy
	ina
	bne     L00F9
	inx
L00F9:	jsr     pushax
	ldy     #$09
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     tosaddax
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	lda     (sp)
	ina
	bra     L02DB
L00ED:	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$2F
	jsr     incaxy
L02E0:	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$0D
	jsr     subysp
	lda     #<(_saveBuf)
	sta     _saveptr
	lda     #>(_saveBuf)
	sta     _saveptr+1
	lda     #<(_INTRO_FILENR)
	ldx     #>(_INTRO_FILENR)
	jsr     _lynx_load
	ldy     #$00
	jsr     _intro
	jsr     _readSaveData
	lda     #<(_saveBuf)
	ldx     #>(_saveBuf)
	jsr     pushax
	lda     #<(L0109)
	ldx     #>(L0109)
	jsr     _strcmp
	cpx     #$00
	bne     L0307
	cmp     #$00
	beq     L0106
L0307:	jsr     _resetSaveData
L0106:	lda     _saveptr
	sta     ptr1
	lda     _saveptr+1
	sta     ptr1+1
	ldy     #$06
	lda     (ptr1),y
	and     #$01
	sta     _musicEnabled
	lda     _saveptr
	sta     ptr1
	lda     _saveptr+1
	sta     ptr1+1
	lda     (ptr1),y
	cmp     #$80
	ror     a
	and     #$01
	sta     _altview
	lda     _saveptr
	sta     ptr1
	lda     _saveptr+1
	sta     ptr1+1
	lda     (ptr1),y
	lsr     a
	lsr     a
	and     #$01
	sta     _lastmove
L030C:	stz     _reset
	stz     _halted
	stz     _ingame
	jsr     _stopPCMSample
	lda     #<(_MENU_FILENR)
	ldx     #>(_MENU_FILENR)
	jsr     _lynx_load
	lda     _menutune
	bne     L0125
	tay
	jsr     _lynx_snd_stop
	jsr     _play_Tune
L0125:	ldy     #$00
	jsr     _menu
	ldy     #$04
	sta     (sp),y
	lda     (sp),y
	jne     L02F0
	jsr     pusha
	jsr     _selectGame
	ldy     #$0B
	sta     (sp),y
	cmp     #$04
	bcs     L02EC
	lda     (sp),y
	cmp     #$03
	bcs     L0132
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$06
	sta     (sp),y
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$08
	sta     (sp),y
	bra     L0310
L0132:	lda     #$60
L0310:	jsr     pusha
	jsr     _selectLevel
	ldy     #$0C
	sta     (sp),y
L02EC:	lda     #$01
	ldy     #$09
	jmp     L02E5
L0145:	jsr     _stopPCMSample
	ldy     #$00
	jsr     _lynx_snd_stop
	stz     _menutune
	lda     #<(_GAME_FILENR)
	ldx     #>(_GAME_FILENR)
	jsr     _lynx_load
	ldy     #$0B
	lda     (sp),y
	cmp     #$03
	bcs     L0152
	iny
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	jsr     _game
	ldy     #$08
	sta     (sp),y
	lda     _reset
	bne     L015E
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	jsr     _addGame
	jsr     _writeSaveData
	bra     L015E
L0152:	iny
	lda     (sp),y
	jsr     pusha
	lda     #$FF
	jsr     pusha
	jsr     _game
L015E:	jsr     _stopPCMSample
	lda     _menutune
	bne     L0163
	tay
	jsr     _lynx_snd_stop
	jsr     _play_Tune
L0163:	lda     #<(_MENU_FILENR)
	ldx     #>(_MENU_FILENR)
	jsr     _lynx_load
	lda     _reset
	bne     L0147
	ldy     #$0B
	lda     (sp),y
	cmp     #$03
	bcs     L016B
	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	jsr     _showHistory
	jsr     _stopPCMSample
	lda     #<(_MENU_FILENR)
	ldx     #>(_MENU_FILENR)
	jsr     _lynx_load
L016B:	lda     #$01
	jsr     pusha
	jsr     _askPlayAgain
	ldy     #$09
	sta     (sp),y
	cmp     #$01
	bne     L02ED
	dey
	lda     (sp),y
	jsr     pusha
	jsr     _selectLevel
	ldy     #$0C
L02E5:	sta     (sp),y
L0147:	ldy     #$09
L02ED:	lda     (sp),y
	jeq     L030C
	lda     _reset
	jne     L030C
	ldy     #$0B
	lda     (sp),y
	cmp     #$04
	jcs     L030C
	iny
	lda     (sp),y
	tax
	jpl     L0145
	jmp     L030C
L02F0:	lda     (sp),y
	cmp     #$01
	jne     L0300
	jsr     _select2PMode
	sta     (sp)
	cmp     #$01
	bne     L02F3
	dea
	jsr     pusha
	jsr     _selectGame
	ldy     #$0B
	sta     (sp),y
	cmp     #$03
	bcs     L02F1
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$08
	sta     (sp),y
L02F1:	lda     #$01
	jmp     L02FD
L02F3:	lda     (sp)
	bne     L02F6
	ina
	jsr     pusha
	jsr     _selectGame
	ldy     #$0B
	sta     (sp),y
	cmp     #$03
	bcs     L02F5
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$0D
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$08
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	clc
	adc     #$02
	jsr     pusha
	jsr     _selectGame
	ldy     #$0A
	sta     (sp),y
	cmp     #$03
	bcs     L02F4
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$0C
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$07
	bra     L02E7
L02F4:	lda     #$03
	iny
L02E7:	sta     (sp),y
L02F5:	lda     #$01
	jmp     L02FD
L02F6:	lda     #$00
	jmp     L02FD
L01AC:	jsr     _stopPCMSample
	ldy     #$00
	jsr     _lynx_snd_stop
	stz     _menutune
	lda     #<(_GAME2P_FILENR)
	ldx     #>(_GAME2P_FILENR)
	jsr     _lynx_load
	ldy     #$0B
	lda     (sp),y
	cmp     #$03
	jcs     L01B8
	lda     (sp)
	bne     L01BA
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	lda     (sp),y
	jsr     pusha
	jsr     _game2P
	ldy     #$01
	jsr     staxysp
	cpx     #$00
	bne     L0308
	cmp     #$FF
	jeq     L030B
L0308:	lda     _reset
	bne     L02F7
	ldy     #$01
	lda     (sp),y
	ldy     #$08
	sta     (sp),y
	ldy     #$03
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$09
	lda     (sp),y
	jsr     pusha
	jsr     _addGame
	ldy     #$02
	lda     (sp),y
	ldy     #$07
	sta     (sp),y
	ldy     #$0A
	lda     (sp),y
	jsr     pusha
	ldy     #$08
	bra     L0311
L02F7:	lda     #$FF
	bra     L030B
L01BA:	ldy     #$08
	lda     (sp),y
	jsr     pusha
	jsr     _netgame
	ldy     #$03
	sta     (sp),y
	cmp     #$FF
	bcs     L01EA
	lda     _reset
	bne     L01EA
	lda     (sp),y
	ldy     #$08
	sta     (sp),y
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$09
L0311:	lda     (sp),y
	jsr     pusha
	jsr     _addGame
	jsr     _writeSaveData
	bra     L01EA
L01B8:	lda     (sp)
	bne     L01E4
	dea
	jsr     pusha
	jsr     pusha
	jsr     _game2P
	bra     L030B
L01E4:	lda     #$FF
	jsr     pusha
	jsr     _netgame
L030B:	ldy     #$03
	sta     (sp),y
L01EA:	jsr     _stopPCMSample
	lda     _menutune
	bne     L01EF
	tay
	jsr     _lynx_snd_stop
	jsr     _play_Tune
L01EF:	lda     #<(_MENU_FILENR)
	ldx     #>(_MENU_FILENR)
	jsr     _lynx_load
	ldy     #$03
	lda     (sp),y
	cmp     #$FF
	bcs     L02FA
	lda     _reset
	beq     L02FB
L02FA:	lda     #$00
	bra     L02FD
L02FB:	ldy     #$0B
	lda     (sp),y
	cmp     #$03
	bcs     L01F9
	lda     (sp)
	bne     L01FB
	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	jsr     _showHistory2P
	bra     L0203
L01FB:	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	ldy     #$0B
	lda     (sp),y
	jsr     pusha
	jsr     _showHistory
L0203:	jsr     _stopPCMSample
	lda     #<(_MENU_FILENR)
	ldx     #>(_MENU_FILENR)
	jsr     _lynx_load
L01F9:	lda     #$00
	jsr     pusha
	jsr     _askPlayAgain
L02FD:	ldy     #$09
	sta     (sp),y
	lda     (sp),y
	jeq     L030C
	lda     _reset
	jne     L030C
	ldy     #$0B
	lda     (sp),y
	cmp     #$04
	jcc     L01AC
	jmp     L030C
L0300:	lda     (sp),y
	cmp     #$02
	bne     L0302
	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	jsr     _stats
	jmp     L030C
L0302:	lda     (sp),y
	cmp     #$03
	bne     L0304
	jsr     _options
	lda     _saveptr
	sta     sreg
	lda     _saveptr+1
	sta     sreg+1
	lda     _altview
	asl     a
	and     _musicEnabled
	sta     ptr1
	lda     #$00
	tax
	stz     ptr1+1
	lda     _lastmove
	jsr     aslax2
	and     ptr1
	pha
	txa
	and     ptr1+1
	pla
	ldy     #$06
	sta     (sreg),y
	jsr     _writeSaveData
	jmp     L030C
L0304:	lda     (sp),y
	cmp     #$04
	bne     L0306
	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	jsr     _tutorial
	jmp     L030C
L0306:	lda     (sp),y
	cmp     #$05
	jne     L030C
	jsr     _stopPCMSample
	lda     #<(_CREDITS_FILENR)
	ldx     #>(_CREDITS_FILENR)
	jsr     _lynx_load
	jsr     _credits
	jmp     L030C

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ checkInput (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_checkInput: near

.segment	"CODE"

	jsr     decsp5
	lda     _reset
	jne     L0235
L0234:	jsr     _kbhit
	tax
	jeq     L023B
	jsr     _cgetc
	cmp     #$31
	jeq     L0281
	cmp     #$32
	jeq     L0290
	cmp     #$33
	jeq     L02A9
	cmp     #$3F
	jeq     L023B
	cmp     #$46
	beq     L023D
	cmp     #$50
	beq     L0242
	cmp     #$52
	jeq     L0276
	jmp     L023B
L023D:	lda     #$01
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	jmp     L023B
L0242:	lda     _halted
	beq     L0243
	stz     _halted
	lda     #<(_backupPal)
	ldx     #>(_backupPal)
	jsr     _tgi_setpalette
	ldy     #$00
	jsr     _lynx_snd_continue
	jmp     L023B
L0243:	jsr     _tgi_getpalette
	jsr     stax0sp
	lda     #$00
	ldy     #$02
L031D:	sta     (sp),y
	cmp     #$10
	jcs     L024E
	lda     #<(_backupPal)
	ldx     #>(_backupPal)
	clc
	adc     (sp),y
	bcc     L0257
	inx
L0257:	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	jsr     staspidx
	ldy     #$02
	ldx     #$00
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	clc
	adc     #<(_backupPal)
	sta     sreg
	txa
	adc     #>(_backupPal)
	sta     sreg+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	clc
	adc     (sp)
	sta     ptr1
	txa
	ldy     #$01
	adc     (sp),y
	sta     ptr1+1
	lda     (ptr1)
	sta     (sreg)
	iny
	lda     (sp),y
	tay
	lda     _backupPal,y
	ldx     #$00
	and     #$0F
	asl     a
	bcc     L0312
	inx
L0312:	sta     sreg
	stx     sreg+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	sta     ptr1
	txa
	clc
	adc     #>(_backupPal)
	sta     ptr1+1
	ldy     #<(_backupPal)
	lda     (ptr1),y
	and     #$0F
	clc
	adc     sreg
	ldx     sreg+1
	bcc     L031C
	inx
L031C:	sta     sreg
	stx     sreg+1
	ldx     #$00
	ldy     #$02
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	sta     ptr1
	txa
	clc
	adc     #>(_backupPal)
	sta     ptr1+1
	ldy     #<(_backupPal)
	lda     (ptr1),y
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	clc
	adc     sreg
	pha
	lda     #$00
	adc     sreg+1
	tax
	pla
	jsr     shrax2
	ldy     #$03
	jsr     staxysp
	ldy     #$02
	lda     (sp),y
	tax
	iny
	lda     (sp),y
	sta     _grayPal,x
	dey
	ldx     #$00
	lda     (sp),y
	ldy     #$10
	jsr     incaxy
	clc
	adc     #<(_grayPal)
	sta     ptr1
	txa
	adc     #>(_grayPal)
	sta     ptr1+1
	ldy     #$04
	jsr     ldaxysp
	jsr     shlax4
	ldy     #$03
	ora     (sp),y
	pha
	txa
	iny
	ora     (sp),y
	pla
	sta     (ptr1)
	ldy     #$02
	lda     (sp),y
	ina
	jmp     L031D
L024E:	lda     #<(_grayPal)
	ldx     #>(_grayPal)
	jsr     _tgi_setpalette
	lda     #$01
	sta     _halted
	ldy     #$00
	jsr     _lynx_snd_pause
	jmp     L023B
L0276:	lda     _halted
	beq     L0277
	stz     _halted
	lda     #<(_backupPal)
	ldx     #>(_backupPal)
	jsr     _tgi_setpalette
	ldy     #$00
	jsr     _lynx_snd_continue
L0277:	lda     #$01
	sta     _reset
	bra     L023B
L0281:	lda     _ingame
	beq     L023B
	lda     _halted
	bne     L023B
	lda     _flipflop
	beq     L0286
	lda     _altview
	jsr     bnega
	sta     _altview
	bra     L028A
L0286:	lda     _lastmove
	jsr     bnega
	sta     _lastmove
L028A:	lda     _flipflop
	jsr     bnega
	sta     _flipflop
	bra     L023B
L0290:	lda     _halted
	bne     L023B
	lda     _musicEnabled
	beq     L0293
	ldy     #$00
	jsr     _lynx_snd_stop
	stz     _menutune
	lda     _ingame
	beq     L031A
	lda     _tunenum
	cmp     #$02
	bcc     L031E
L031A:	stz     _musicEnabled
	bra     L023B
L0293:	ina
	sta     _musicEnabled
	ina
	sta     _tunenum
L031E:	jsr     _stopPCMSample
	jsr     _play_Tune
	bra     L023B
L02A9:	lda     _halted
	beq     L023B
	lda     _ingame
	bne     L023B
	jsr     _resetSaveData
L023B:	lda     _halted
	beq     L031F
	lda     _reset
	jeq     L0234
L0235:	lda     #$00
L031F:	jsr     _joy_read
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ play_PCM (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_play_PCM: near

.segment	"CODE"

	jsr     _stopPCMSample
	jsr     ldax0sp
	jsr     _openn
	jsr     _playPCMSample
	jmp     incsp2

.endproc

