;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_tgi_ioctl
	.import		_font000000
	.import		_font000001
	.import		_font000002
	.import		_font000003
	.import		_font000004
	.import		_font000005
	.import		_font000006
	.import		_font000007
	.import		_font000008
	.import		_font000009
	.import		_font000010
	.import		_font000011
	.import		_font000012
	.import		_font000013
	.import		_font000014
	.import		_font000015
	.import		_font000016
	.import		_font000017
	.import		_font000018
	.import		_font000019
	.import		_font000020
	.import		_font000021
	.import		_font000022
	.import		_font000023
	.import		_font000024
	.import		_font000025
	.import		_font001000
	.import		_font001001
	.import		_font001002
	.import		_font001003
	.import		_font001004
	.import		_font001005
	.import		_font001006
	.import		_font001007
	.import		_font001008
	.import		_font001009
	.import		_font001010
	.import		_font001011
	.import		_font001012
	.import		_font001013
	.import		_font001014
	.import		_font001015
	.import		_font001016
	.import		_font001017
	.import		_font001018
	.import		_font001019
	.import		_font001020
	.import		_font001021
	.import		_font001022
	.import		_font001023
	.import		_font001024
	.import		_font001025
	.import		_font002000
	.import		_font002001
	.import		_font002002
	.import		_font002003
	.import		_font002004
	.import		_font002005
	.import		_font002006
	.import		_font002007
	.import		_font002008
	.import		_font002009
	.import		_font002010
	.import		_font002011
	.import		_font002012
	.import		_font002013
	.import		_font002014
	.import		_font002015
	.import		_font002016
	.import		_font002017
	.import		_font002018
	.import		_font002019
	.export		_spFont
	.export		_CharSize
	.export		_sp_font
	.export		_getCharTile
	.export		_textxy

.segment	"DATA"

_spFont:
	.addr	_font000000
	.addr	_font000001
	.addr	_font000002
	.addr	_font000003
	.addr	_font000004
	.addr	_font000005
	.addr	_font000006
	.addr	_font000007
	.addr	_font000008
	.addr	_font000009
	.addr	_font000010
	.addr	_font000011
	.addr	_font000012
	.addr	_font000013
	.addr	_font000014
	.addr	_font000015
	.addr	_font000016
	.addr	_font000017
	.addr	_font000018
	.addr	_font000019
	.addr	_font000020
	.addr	_font000021
	.addr	_font000022
	.addr	_font000023
	.addr	_font000024
	.addr	_font000025
	.addr	_font001000
	.addr	_font001001
	.addr	_font001002
	.addr	_font001003
	.addr	_font001004
	.addr	_font001005
	.addr	_font001006
	.addr	_font001007
	.addr	_font001008
	.addr	_font001009
	.addr	_font001010
	.addr	_font001011
	.addr	_font001012
	.addr	_font001013
	.addr	_font001014
	.addr	_font001015
	.addr	_font001016
	.addr	_font001017
	.addr	_font001018
	.addr	_font001019
	.addr	_font001020
	.addr	_font001021
	.addr	_font001022
	.addr	_font001023
	.addr	_font001024
	.addr	_font001025
	.addr	_font002000
	.addr	_font002001
	.addr	_font002002
	.addr	_font002003
	.addr	_font002004
	.addr	_font002005
	.addr	_font002006
	.addr	_font002007
	.addr	_font002008
	.addr	_font002009
	.addr	_font002010
	.addr	_font002011
	.addr	_font002012
	.addr	_font002013
	.addr	_font002014
	.addr	_font002015
	.addr	_font002016
	.addr	_font002017
	.addr	_font002018
	.addr	_font002019
_CharSize:
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$03
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$05
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$03
	.byte	$03
	.byte	$04
	.byte	$03
	.byte	$06
	.byte	$05
	.byte	$04
	.byte	$04
	.byte	$05
	.byte	$04
	.byte	$05
	.byte	$03
	.byte	$05
	.byte	$05
	.byte	$06
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$05
	.byte	$04
_sp_font:
	.byte	$C4
	.byte	$10
	.byte	$01
	.word	$0000
	.addr	_font000000
	.word	$0000
	.word	$0000
	.word	$0100
	.word	$0100
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF

; ---------------------------------------------------------------
; signed char __near__ getCharTile (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getCharTile: near

.segment	"CODE"

	lda     (sp)
	cmp     #$41
	bcc     L0129
	cmp     #$5B
	bcs     L0129
	ldx     #$00
	lda     (sp)
	ldy     #$41
	jsr     decaxy
	jmp     incsp1
L0129:	lda     (sp)
	cmp     #$61
	bcc     L012E
	cmp     #$7B
	bcs     L012E
	ldx     #$00
	lda     (sp)
	ldy     #$61
	jsr     decaxy
	ldy     #$1A
	jsr     incaxy
	jmp     incsp1
L012E:	lda     (sp)
	cmp     #$30
	bcc     L0133
	cmp     #$3A
	bcs     L0133
	ldx     #$00
	lda     (sp)
	ldy     #$30
	jsr     decaxy
	ldy     #$34
	jsr     incaxy
	jmp     incsp1
L0133:	lda     (sp)
	cmp     #$3A
	bne     L0135
	ldx     #$00
	lda     #$3E
	jmp     incsp1
L0135:	lda     (sp)
	cmp     #$3B
	bne     L0137
	ldx     #$00
	lda     #$3F
	jmp     incsp1
L0137:	lda     (sp)
	cmp     #$21
	bne     L0139
	ldx     #$00
	lda     #$40
	jmp     incsp1
L0139:	lda     (sp)
	cmp     #$2D
	bne     L013B
	ldx     #$00
	lda     #$41
	jmp     incsp1
L013B:	lda     (sp)
	cmp     #$2B
	bne     L013D
	ldx     #$00
	lda     #$42
	jmp     incsp1
L013D:	lda     (sp)
	cmp     #$3C
	bne     L013F
	ldx     #$00
	lda     #$43
	jmp     incsp1
L013F:	lda     (sp)
	cmp     #$3E
	bne     L0141
	ldx     #$00
	lda     #$44
	jmp     incsp1
L0141:	lda     (sp)
	cmp     #$28
	bne     L0143
	ldx     #$00
	lda     #$45
	jmp     incsp1
L0143:	lda     (sp)
	cmp     #$29
	bne     L0145
	ldx     #$00
	lda     #$46
	jmp     incsp1
L0145:	lda     (sp)
	cmp     #$2E
	bne     L0147
	ldx     #$00
	lda     #$47
	jmp     incsp1
L0147:	lda     (sp)
	cmp     #$2F
	bne     L00F3
	ldx     #$FF
	lda     #$FE
	jmp     incsp1
L00F3:	ldx     #$FF
	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ textxy (int, int, __near__ unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_textxy: near

.segment	"CODE"

	jsr     decsp2
	ldy     #$05
	jsr     ldaxysp
	sta     _sp_font+9
	stx     _sp_font+9+1
	ldy     #$07
	jsr     ldaxysp
	sta     _sp_font+7
	stx     _sp_font+7+1
	lda     #$00
	ldy     #$01
L0149:	sta     (sp),y
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	tay
	lda     (ptr1),y
	bne     L014A
	jmp     incsp8
L014A:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	tay
	lda     (ptr1),y
	jsr     pusha
	jsr     _getCharTile
	sta     (sp)
	cmp     #$FE
	bne     L0148
	lda     #$09
	clc
	adc     _sp_font+9
	sta     _sp_font+9
	bcc     L010E
	inc     _sp_font+9+1
L010E:	ldy     #$07
	jsr     ldaxysp
	sta     _sp_font+7
	stx     _sp_font+7+1
	bra     L00FE
L0148:	lda     (sp)
	tax
	bmi     L0112
	ldx     #$00
	lda     (sp)
	bpl     L0118
	dex
L0118:	jsr     aslax1
	clc
	adc     #<(_spFont)
	tay
	txa
	adc     #>(_spFont)
	tax
	tya
	jsr     ldaxi
	sta     _sp_font+5
	stx     _sp_font+5+1
	lda     #$00
	jsr     pusha
	lda     #<(_sp_font)
	ldx     #>(_sp_font)
	jsr     _tgi_ioctl
	lda     (sp)
	tay
	lda     _CharSize,y
	clc
	adc     _sp_font+7
	sta     _sp_font+7
	lda     #$00
	adc     _sp_font+7+1
	sta     _sp_font+7+1
	bra     L00FE
L0112:	lda     #$02
	clc
	adc     _sp_font+7
	sta     _sp_font+7
	bcc     L00FE
	inc     _sp_font+7+1
L00FE:	ldy     #$01
	lda     (sp),y
	ina
	jmp     L0149

.endproc

