;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_sprintf
	.import		_tgi_setpalette
	.import		_tgi_ioctl
	.import		_joy_masks
	.import		_clock
	.export		_menubg1_redir
	.export		_menubg1_pal
	.import		_textxy
	.import		_checkInput
	.import		_play_PCM
	.import		_lynx_snd_play
	.import		_lynx_snd_stop
	.import		_musicptr
	.import		_menubg1
	.import		_menubg2
	.import		_menubg3
	.import		_marker
	.import		_markeron
	.import		_select
	.import		_reset
	.import		_musicEnabled
	.import		_altview
	.import		_lastmove
	.import		_saveptr
	.export		_bgcount
	.export		_menubg
	.import		_SAMPLE2_FILENR
	.export		_sp_menubg
	.export		_sp_marker
	.export		_sp_select
	.export		_offset
	.export		_menu
	.export		_select2PMode
	.export		_selectGame
	.export		_selectLevel
	.export		_askPlayAgain
	.export		_options

.segment	"MENU_DATA"

_menubg1_redir:
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF
_menubg1_pal:
	.byte	$02
	.byte	$02
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$06
	.byte	$04
	.byte	$0F
	.byte	$0B
	.byte	$0C
	.byte	$33
	.byte	$34
	.byte	$47
	.byte	$34
	.byte	$34
	.byte	$45
	.byte	$46
	.byte	$46
	.byte	$47
	.byte	$58
	.byte	$58
	.byte	$6B
	.byte	$3E
	.byte	$FF
	.byte	$4E
	.byte	$5F
_bgcount:
	.byte	$00
_menubg:
	.addr	_menubg1
	.addr	_menubg2
	.addr	_menubg3
	.addr	_menubg2
_sp_menubg:
	.byte	$C0
	.byte	$10
	.byte	$01
	.word	$0000
	.addr	_menubg1
	.word	$0000
	.word	$0000
	.word	$0100
	.word	$0100
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF
_sp_marker:
	.byte	$C4
	.byte	$10
	.byte	$01
	.word	$0000
	.addr	_marker
	.word	$003F
	.word	$0010
	.word	$0100
	.word	$0100
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF
_sp_select:
	.byte	$C0
	.byte	$10
	.byte	$01
	.word	$0000
	.addr	_select
	.word	$0000
	.word	$0000
	.word	$0100
	.word	$0100
	.byte	$01
	.byte	$23
	.byte	$45
	.byte	$67
	.byte	$89
	.byte	$AB
	.byte	$CD
	.byte	$EF
_offset:
	.byte	$1B
	.byte	$00
	.byte	$1E
	.byte	$25
	.byte	$27

.segment	"MENU_RODATA"

L0199:
	.byte	$53,$6C,$6F,$74,$20,$25,$69,$20,$3A,$20,$52,$61,$6E,$6B,$20,$25
	.byte	$69,$20,$20,$20,$47,$61,$6D,$65,$64,$20,$32,$35,$34,$2B,$00
L023A:
	.byte	$28,$20,$30,$20,$3A,$20,$57,$65,$61,$6B,$20,$20,$20,$20,$20,$31
	.byte	$30,$20,$3A,$20,$53,$74,$72,$6F,$6E,$67,$20,$29,$00
L01A3:
	.byte	$53,$6C,$6F,$74,$20,$25,$69,$20,$3A,$20,$52,$61,$6E,$6B,$20,$25
	.byte	$69,$20,$20,$20,$47,$61,$6D,$65,$73,$20,$25,$69,$00
L02CD:
	.byte	$50,$72,$65,$73,$73,$20,$41,$20,$74,$6F,$20,$73,$65,$6C,$65,$63
	.byte	$74,$20,$61,$6E,$20,$6F,$70,$74,$69,$6F,$6E,$00
L0334:
	.byte	$53,$61,$76,$65,$20,$61,$6E,$64,$20,$65,$78,$69,$74,$20,$6F,$70
	.byte	$74,$69,$6F,$6E,$73,$20,$6D,$65,$6E,$75,$00
L02B5:
	.byte	$59,$65,$73,$2C,$20,$63,$68,$61,$6E,$67,$69,$6E,$67,$20,$43,$50
	.byte	$55,$20,$73,$74,$72,$65,$6E,$67,$74,$68,$00
L0368:
	.byte	$50,$72,$65,$73,$73,$20,$41,$20,$74,$6F,$20,$63,$68,$61,$6E,$67
	.byte	$65,$20,$6F,$70,$74,$69,$6F,$6E,$73,$00
L0241:
	.byte	$50,$72,$65,$73,$73,$20,$41,$20,$74,$6F,$20,$73,$74,$61,$72,$74
	.byte	$20,$74,$68,$65,$20,$67,$61,$6D,$65,$00
L0226:
	.byte	$53,$45,$4C,$45,$43,$54,$20,$54,$48,$45,$20,$43,$50,$55,$20,$53
	.byte	$54,$52,$45,$4E,$47,$54,$48,$00
L0107:
	.byte	$53,$45,$4C,$45,$43,$54,$20,$41,$20,$32,$20,$50,$4C,$41,$59,$45
	.byte	$52,$53,$20,$4D,$4F,$44,$45,$00
L0325:
	.byte	$53,$68,$6F,$77,$20,$61,$6C,$74,$65,$72,$6E,$61,$74,$65,$20,$76
	.byte	$69,$65,$77,$73,$3A,$00
L017B:
	.byte	$53,$45,$4C,$45,$43,$54,$20,$50,$31,$20,$53,$41,$56,$45,$20,$53
	.byte	$4C,$4F,$54,$00
L0181:
	.byte	$53,$45,$4C,$45,$43,$54,$20,$50,$32,$20,$53,$41,$56,$45,$20,$53
	.byte	$4C,$4F,$54,$00
L0111:
	.byte	$43,$6F,$6D,$6C,$79,$6E,$78,$20,$63,$6F,$6E,$6E,$65,$63,$74,$69
	.byte	$6F,$6E,$00
L0172:
	.byte	$53,$45,$4C,$45,$43,$54,$20,$41,$20,$53,$41,$56,$45,$20,$53,$4C
	.byte	$4F,$54,$00
L01B0:
	.byte	$53,$6C,$6F,$74,$20,$25,$69,$20,$3A,$20,$45,$6D,$70,$74,$79,$00
L032A:
	.byte	$53,$68,$6F,$77,$20,$6C,$61,$73,$74,$20,$6D,$6F,$76,$65,$3A,$00
L022B:
	.byte	$43,$50,$55,$20,$73,$74,$72,$65,$6E,$67,$74,$68,$3A,$00
L01BB:
	.byte	$50,$6C,$61,$79,$20,$55,$6E,$72,$61,$6E,$6B,$65,$64,$00
L010C:
	.byte	$53,$61,$6D,$65,$20,$63,$6F,$6E,$73,$6F,$6C,$65,$00
L0320:
	.byte	$47,$41,$4D,$45,$20,$4F,$50,$54,$49,$4F,$4E,$53,$00
L02A9:
	.byte	$50,$4C,$41,$59,$20,$41,$47,$41,$49,$4E,$3F,$00
L032F:
	.byte	$4D,$75,$73,$69,$63,$73,$3A,$00
L034E:
	.byte	$59,$65,$73,$00
L0361:
	.byte	$4F,$66,$66,$00
L0341	:=	L034E+0
L02AE	:=	L034E+0
L02BA:
	.byte	$4E,$6F,$00
L02C0	:=	L02BA+0
L035B:
	.byte	$4F,$6E,$00
L0347	:=	L02BA+0
L0354	:=	L02BA+0
L022F	:=	L01A3+26
L0116:
	.byte	$3E,$00
L033A	:=	L0116+0
L01C0	:=	L0116+0
L02C6	:=	L0116+0

; ---------------------------------------------------------------
; unsigned char __near__ menu (void)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_menu: near

.segment	"MENU_CODE"

	jsr     decsp4
	lda     #$00
	jsr     pusha
	jsr     pusha
	ina
	jsr     pusha
	jsr     pusha
	lda     #<(_marker)
	sta     _sp_marker+5
	lda     #>(_marker)
	sta     _sp_marker+5+1
	jmp     L008D
L03C4:	lda     _bgcount
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	lsr     a
	asl     a
	bcc     L03D3
	inx
	clc
L03D3:	adc     #<(_menubg)
	tay
	txa
	adc     #>(_menubg)
	tax
	tya
	jsr     ldaxi
	sta     _sp_menubg+5
	stx     _sp_menubg+5+1
	lda     _bgcount
	ina
	and     #$7F
	sta     _bgcount
	lda     #$00
	jsr     pusha
	lda     #<(_sp_menubg)
	ldx     #>(_sp_menubg)
	jsr     _tgi_ioctl
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	lda     #$0C
	jsr     tosumula0
	ldy     #$10
	jsr     incaxy
	sta     _sp_marker+9
	stx     _sp_marker+9+1
	lda     #$00
	jsr     pusha
	lda     #<(_sp_marker)
	ldx     #>(_sp_marker)
	jsr     _tgi_ioctl
	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L00A5:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L00A5
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	jsr     _checkInput
	ldy     #$01
	sta     (sp),y
	lda     _joy_masks+4
	and     (sp),y
	pha
	pla
	beq     L00AD
	lda     (sp)
	bne     L00AD
	tya
	iny
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	sta     (sp)
L00AD:	ldx     #$00
	lda     _joy_masks
	ldy     #$01
	and     (sp),y
	pha
	pla
	beq     L03D0
	lda     (sp)
	bne     L03D0
	ldy     #$03
	lda     (sp),y
	jsr     incax5
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	ldy     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	sta     (sp)
	ldx     #$00
L03D0:	lda     _joy_masks+1
	ldy     #$01
	and     (sp),y
	pha
	pla
	beq     L03D1
	lda     (sp)
	bne     L00C8
	ldy     #$03
	lda     (sp),y
	ina
	bne     L00D2
	inx
L00D2:	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	ldy     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	sta     (sp)
L00C8:	ldy     #$01
L03D1:	lda     (sp),y
	bne     L008D
	sta     (sp)
L008D:	ldy     #$02
	lda     (sp),y
	bne     L008F
	lda     _reset
	beq     L008E
L008F:	lda     #$00
	bra     L03CF
L008E:	tax
	jmp     L03C4
L03CF:	jsr     pusha
	lda     #<(_sp_menubg)
	ldx     #>(_sp_menubg)
	jsr     _tgi_ioctl
	lda     #<(_markeron)
	sta     _sp_marker+5
	lda     #>(_markeron)
	sta     _sp_marker+5+1
	ldy     #$03
	lda     (sp),y
	jsr     pusha0
	lda     #$0C
	jsr     tosumula0
	ldy     #$10
	jsr     incaxy
	sta     _sp_marker+9
	stx     _sp_marker+9+1
	lda     #$00
	jsr     pusha
	lda     #<(_sp_marker)
	ldx     #>(_sp_marker)
	jsr     _tgi_ioctl
	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L00EA:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L00EA
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	jsr     _clock
	ldy     #$04
	jsr     steaxysp
L00F4:	jsr     _clock
	jsr     pusheax
	ldy     #$0B
	jsr     ldeaxysp
	ldy     #$28
	jsr     inceaxy
	jsr     tosulteax
	bne     L00F4
	ldy     #$03
	ldx     #$00
	lda     (sp),y
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ select2PMode (void)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_select2PMode: near

.segment	"MENU_CODE"

	lda     #$00
	jsr     pusha
	jsr     pusha
	ina
	jsr     pusha
	jmp     L00FD
L00FB:	jsr     pusha
	lda     #<(_sp_select)
	ldx     #>(_sp_select)
	jsr     _tgi_ioctl
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L0107)
	ldx     #>(L0107)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #<(L010C)
	ldx     #>(L010C)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$32
	jsr     pusha0
	lda     #<(L0111)
	ldx     #>(L0111)
	jsr     pushax
	jsr     _textxy
	lda     #$05
	jsr     pusha0
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	lda     #$14
	jsr     tosumula0
	ldy     #$1E
	jsr     incaxy
	jsr     pushax
	lda     #<(L0116)
	ldx     #>(L0116)
	jsr     pushax
	jsr     _textxy
	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L011D:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L011D
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	bra     L0125
L0123:	jsr     _checkInput
	sta     (sp)
L0125:	lda     (sp)
	beq     L03D7
	lda     _reset
	beq     L0123
	bra     L03D7
L012B:	jsr     _checkInput
	sta     (sp)
L03D7:	lda     (sp)
	bne     L012F
	lda     _reset
	beq     L012B
L012F:	lda     _joy_masks+4
	and     (sp)
	pha
	pla
	beq     L03DB
	lda     #$01
	tay
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03DB:	lda     _joy_masks+5
	and     (sp)
	pha
	pla
	beq     L03DD
	lda     #$01
	tay
	sta     (sp),y
	ina
	iny
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03DD:	lda     _joy_masks
	and     (sp)
	pha
	pla
	beq     L03E0
	ldy     #$02
	lda     (sp),y
	ina
	and     #$01
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03E0:	lda     _joy_masks+1
	and     (sp)
	pha
	pla
	beq     L00FD
	ldy     #$02
	lda     (sp),y
	ina
	and     #$01
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L00FD:	ldy     #$01
	lda     (sp),y
	bne     L03D6
	lda     _reset
	jeq     L00FB
L03D6:	iny
	ldx     #$00
	lda     (sp),y
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ selectGame (signed char)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_selectGame: near

.segment	"MENU_CODE"

	jsr     decsp1
	lda     #$00
	jsr     pusha
	jsr     pusha
	ina
	jsr     pusha
	ldy     #$23
	jsr     subysp
	jmp     L0165
L0163:	jsr     pusha
	lda     #<(_sp_select)
	ldx     #>(_sp_select)
	jsr     _tgi_ioctl
	ldy     #$27
	lda     (sp),y
	bne     L03E9
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L0172)
	ldx     #>(L0172)
	bra     L03F8
L03E9:	lda     (sp),y
	cmp     #$01
	bne     L0175
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L017B)
	ldx     #>(L017B)
	bra     L03F8
L0175:	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L0181)
	ldx     #>(L0181)
L03F8:	jsr     pushax
	jsr     _textxy
	lda     #$00
	ldy     #$26
	sta     (sp),y
	tax
L03EB:	lda     (sp),y
	cmp     #$03
	jcs     L03EC
	sta     ptr1
	stz     ptr1+1
	iny
	lda     (sp),y
	bpl     L018E
	dex
L018E:	jsr     decax2
	cpx     ptr1+1
	bne     L03F7
	cmp     ptr1
	jeq     L0185
L03F7:	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$28
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jeq     L018F
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$28
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$FF
	bne     L0193
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L0199)
	ldx     #>(L0199)
	jsr     pushax
	ldy     #$2A
	ldx     #$00
	lda     (sp),y
	ina
	bne     L019C
	inx
L019C:	jsr     pushax
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$2E
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	lda     #$18
	jsr     tosudiva0
	jsr     pushax
	ldy     #$08
	jmp     L03E8
L0193:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L01A3)
	ldx     #>(L01A3)
	jsr     pushax
	ldy     #$2A
	ldx     #$00
	lda     (sp),y
	ina
	bne     L01A6
	inx
L01A6:	jsr     pushax
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$2E
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	ldy     #$09
	jsr     incaxy
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	lda     #$18
	jsr     tosudiva0
	jsr     pushax
	lda     _saveptr
	ldx     _saveptr+1
	jsr     pushax
	ldy     #$30
	lda     (sp),y
	jsr     pusha0
	lda     #$28
	jsr     tosumula0
	jsr     incax8
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$0A
	bra     L03E8
L018F:	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L01B0)
	ldx     #>(L01B0)
	jsr     pushax
	ldy     #$2A
	ldx     #$00
	lda     (sp),y
	ina
	bne     L01B3
	inx
L01B3:	jsr     pushax
	ldy     #$06
L03E8:	jsr     _sprintf
	lda     #$0F
	jsr     pusha0
	ldy     #$28
	lda     (sp),y
	jsr     pusha0
	lda     #$12
	jsr     tosumula0
	ldy     #$1C
	jsr     incaxy
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	jsr     _textxy
L0185:	ldy     #$26
	ldx     #$00
	lda     (sp),y
	ina
	sta     (sp),y
	jmp     L03EB
L03EC:	lda     #$0F
	jsr     pusha0
	lda     #$52
	jsr     pusha0
	lda     #<(L01BB)
	ldx     #>(L01BB)
	jsr     pushax
	jsr     _textxy
	lda     #$05
	jsr     pusha0
	ldy     #$27
	lda     (sp),y
	jsr     pusha0
	lda     #$12
	jsr     tosumula0
	ldy     #$1C
	jsr     incaxy
	jsr     pushax
	lda     #<(L01C0)
	ldx     #>(L01C0)
	jsr     pushax
	jsr     _textxy
	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L01C7:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L01C7
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	bra     L01CF
L01CD:	jsr     _checkInput
	ldy     #$23
	sta     (sp),y
L01CF:	ldy     #$23
	lda     (sp),y
	beq     L03ED
	lda     _reset
	beq     L01CD
	bra     L03ED
L01D5:	jsr     _checkInput
	ldy     #$23
	sta     (sp),y
L03ED:	lda     (sp),y
	bne     L01D9
	lda     _reset
	beq     L01D5
L01D9:	ldx     #$00
	lda     _joy_masks+4
	and     (sp),y
	pha
	pla
	beq     L03F9
	ldy     #$25
	lda     (sp),y
	sta     ptr1
	stz     ptr1+1
	ldy     #$27
	lda     (sp),y
	bpl     L01E4
	dex
L01E4:	jsr     decax2
	cpx     ptr1+1
	bne     L01DE
	cmp     ptr1
	beq     L03F9
L01DE:	lda     #$01
	ldy     #$24
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03F9:	lda     _joy_masks+5
	ldy     #$23
	and     (sp),y
	pha
	pla
	beq     L03F3
	lda     #$01
	iny
	sta     (sp),y
	lda     #$04
	iny
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03F3:	lda     _joy_masks
	ldy     #$23
	and     (sp),y
	pha
	pla
	beq     L03F5
	ldy     #$25
	lda     (sp),y
	clc
	adc     #$03
	and     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L03F5:	lda     _joy_masks+1
	ldy     #$23
	and     (sp),y
	pha
	pla
	beq     L0165
	ldy     #$25
	lda     (sp),y
	ina
	and     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
L0165:	ldy     #$24
	lda     (sp),y
	bne     L03E6
	lda     _reset
	jeq     L0163
L03E6:	iny
	ldx     #$00
	lda     (sp),y
	ldy     #$28
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; signed char __near__ selectLevel (unsigned char)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_selectLevel: near

.segment	"MENU_CODE"

	lda     (sp)
	jsr     pusha0
	lda     #$18
	jsr     tosudiva0
	ina
	jsr     pusha
	lda     #$00
	jsr     pusha
	ina
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$01
	jsr     pusha
	jsr     decsp5
	ldy     #$09
	lda     (sp),y
	sec
	sbc     #$0B
	bvs     L0217
	eor     #$80
L0217:	jpl     L021C
	lda     #$0A
	jmp     L03FB
L021A:	jsr     pusha
	lda     #<(_sp_select)
	ldx     #>(_sp_select)
	jsr     _tgi_ioctl
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L0226)
	ldx     #>(L0226)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #<(L022B)
	ldx     #>(L022B)
	jsr     pushax
	jsr     _textxy
	lda     sp
	ldx     sp+1
	jsr     pushax
	lda     #<(L022F)
	ldx     #>(L022F)
	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (sp),y
	bpl     L0232
	dex
L0232:	jsr     pushax
	ldy     #$06
	jsr     _sprintf
	lda     #$46
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$36
	jsr     pusha0
	lda     #<(L023A)
	ldx     #>(L023A)
	jsr     pushax
	jsr     _textxy
	ldy     #$06
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	and     #$20
	beq     L023C
	lda     #$05
	jsr     pusha0
	lda     #$5D
	jsr     pusha0
	lda     #<(L0241)
	ldx     #>(L0241)
	jsr     pushax
	jsr     _textxy
L023C:	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L0248:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L0248
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	jsr     _checkInput
	ldy     #$07
	sta     (sp),y
	lda     _joy_masks+4
	and     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     bnega
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L0250
	lda     #$01
	ldy     #$08
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	ldy     #$05
	sta     (sp),y
L0250:	lda     _joy_masks+5
	ldy     #$07
	and     (sp),y
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     bnega
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L025B
	lda     #$FF
	ldy     #$09
	sta     (sp),y
	lda     #$01
	dey
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	ldy     #$05
	sta     (sp),y
L025B:	lda     _joy_masks
	ldy     #$07
	and     (sp),y
	pha
	pla
	bne     L03FC
	lda     _joy_masks+3
	and     (sp),y
	pha
	pla
	beq     L0404
L03FC:	ldy     #$09
	lda     (sp),y
	sec
	sbc     #$0A
	bvc     L0274
	eor     #$80
L0274:	asl     a
	lda     #$00
	rol     a
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     bnega
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L0404
	ldy     #$09
	lda     (sp),y
	ina
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	ldy     #$05
	sta     (sp),y
L0404:	lda     _joy_masks+1
	ldy     #$07
	and     (sp),y
	pha
	pla
	bne     L03FF
	lda     _joy_masks+2
	and     (sp),y
	pha
	pla
	beq     L0405
L03FF:	ldy     #$09
	lda     (sp),y
	sec
	sbc     #$01
	bvs     L0288
	eor     #$80
L0288:	asl     a
	lda     #$00
	rol     a
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     bnega
	jsr     tosandax
	stx     tmp1
	ora     tmp1
	beq     L027C
	ldy     #$09
	lda     (sp),y
	dea
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	ldy     #$05
	sta     (sp),y
L027C:	ldy     #$07
L0405:	lda     (sp),y
	bne     L021C
	ldy     #$05
L03FB:	sta     (sp),y
L021C:	ldy     #$08
	lda     (sp),y
	bne     L03FA
	lda     _reset
	jeq     L021A
L03FA:	iny
	ldx     #$00
	lda     (sp),y
	bpl     L020B
	dex
L020B:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ askPlayAgain (unsigned char)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_askPlayAgain: near

.segment	"MENU_CODE"

	lda     (sp)
	ina
	jsr     pusha
	lda     #$00
	jsr     pusha
	ina
	jsr     pusha
	jsr     pusha
	lda     #$20
	jsr     pusha
	jmp     L029F
L029D:	jsr     pusha
	lda     #<(_sp_select)
	ldx     #>(_sp_select)
	jsr     _tgi_ioctl
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L02A9)
	ldx     #>(L02A9)
	jsr     pushax
	jsr     _textxy
	lda     #$1E
	jsr     pusha0
	lda     #$23
	jsr     pusha0
	lda     #<(L02AE)
	ldx     #>(L02AE)
	jsr     pushax
	jsr     _textxy
	ldy     #$05
	lda     (sp),y
	beq     L02B0
	lda     #$1E
	jsr     pusha0
	lda     #$32
	jsr     pusha0
	lda     #<(L02B5)
	ldx     #>(L02B5)
	jsr     pushax
	jsr     _textxy
	lda     #$1E
	jsr     pusha0
	lda     #$41
	jsr     pusha0
	lda     #<(L02BA)
	ldx     #>(L02BA)
	bra     L0412
L02B0:	lda     #$1E
	jsr     pusha0
	lda     #$32
	jsr     pusha0
	lda     #<(L02C0)
	ldx     #>(L02C0)
L0412:	jsr     pushax
	jsr     _textxy
	lda     #$14
	jsr     pusha0
	ldy     #$07
	lda     (sp),y
	jsr     pusha0
	lda     #$0F
	jsr     tosumula0
	ldy     #$32
	jsr     incaxy
	jsr     pushax
	ldy     #$08
	lda     (sp),y
	jsr     pusha0
	lda     #$0F
	jsr     tosumula0
	jsr     tossubax
	jsr     pushax
	lda     #<(L02C6)
	ldx     #>(L02C6)
	jsr     pushax
	jsr     _textxy
	lda     (sp)
	pha
	ina
	sta     (sp)
	pla
	and     #$20
	beq     L02C8
	lda     #$05
	jsr     pusha0
	lda     #$5D
	jsr     pusha0
	lda     #<(L02CD)
	ldx     #>(L02CD)
	jsr     pushax
	jsr     _textxy
L02C8:	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L02D4:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L02D4
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	jsr     _checkInput
	ldy     #$02
	sta     (sp),y
	lda     _joy_masks+4
	and     (sp),y
	pha
	pla
	beq     L02DC
	dey
	lda     (sp),y
	bne     L02DC
	tya
	ldy     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
L02DC:	ldx     #$00
	lda     _joy_masks
	ldy     #$02
	and     (sp),y
	pha
	pla
	beq     L0413
	dey
	lda     (sp),y
	bne     L0413
	ldy     #$04
	lda     (sp),y
	ina
	bne     L02F3
	inx
L02F3:	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	jsr     tosumodax
	ldy     #$04
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
	ldx     #$00
L0413:	lda     _joy_masks+1
	ldy     #$02
	and     (sp),y
	pha
	pla
	beq     L0414
	dey
	lda     (sp),y
	bne     L02F9
	ldy     #$04
	lda     (sp),y
	ina
	bne     L0303
	inx
L0303:	sta     ptr1
	stx     ptr1+1
	iny
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0406
	inx
L0406:	jsr     pushax
	ldy     #$07
	ldx     #$00
	lda     (sp),y
	jsr     incax2
	jsr     tosumodax
	ldy     #$04
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
L02F9:	iny
L0414:	lda     (sp),y
	bne     L029F
	dey
	sta     (sp),y
L029F:	ldy     #$03
	lda     (sp),y
	bne     L0407
	lda     _reset
	jeq     L029D
L0407:	iny
	ldx     #$00
	lda     (sp),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ options (void)
; ---------------------------------------------------------------

.segment	"MENU_CODE"

.proc	_options: near

.segment	"MENU_CODE"

	lda     #$00
	jsr     pusha
	jsr     pusha
	ina
	jsr     pusha
	jsr     pusha
	lda     #$20
	jsr     pusha
	jmp     L0316
L0314:	jsr     pusha
	lda     #<(_sp_select)
	ldx     #>(_sp_select)
	jsr     _tgi_ioctl
	lda     #$05
	jsr     pusha0
	lda     #$0A
	jsr     pusha0
	lda     #<(L0320)
	ldx     #>(L0320)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #<(L0325)
	ldx     #>(L0325)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$2D
	jsr     pusha0
	lda     #<(L032A)
	ldx     #>(L032A)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$3C
	jsr     pusha0
	lda     #<(L032F)
	ldx     #>(L032F)
	jsr     pushax
	jsr     _textxy
	lda     #$0F
	jsr     pusha0
	lda     #$4B
	jsr     pusha0
	lda     #<(L0334)
	ldx     #>(L0334)
	jsr     pushax
	jsr     _textxy
	lda     #$05
	jsr     pusha0
	ldy     #$06
	lda     (sp),y
	jsr     pusha0
	lda     #$0F
	jsr     tosumula0
	ldy     #$1E
	jsr     incaxy
	jsr     pushax
	lda     #<(L033A)
	ldx     #>(L033A)
	jsr     pushax
	jsr     _textxy
	lda     _altview
	beq     L033C
	lda     #$82
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #<(L0341)
	ldx     #>(L0341)
	bra     L0429
L033C:	lda     #$82
	jsr     pusha0
	lda     #$1E
	jsr     pusha0
	lda     #<(L0347)
	ldx     #>(L0347)
L0429:	jsr     pushax
	jsr     _textxy
	lda     _lastmove
	beq     L0349
	lda     #$82
	jsr     pusha0
	lda     #$2D
	jsr     pusha0
	lda     #<(L034E)
	ldx     #>(L034E)
	bra     L042A
L0349:	lda     #$82
	jsr     pusha0
	lda     #$2D
	jsr     pusha0
	lda     #<(L0354)
	ldx     #>(L0354)
L042A:	jsr     pushax
	jsr     _textxy
	lda     _musicEnabled
	beq     L0356
	lda     #$82
	jsr     pusha0
	lda     #$3C
	jsr     pusha0
	lda     #<(L035B)
	ldx     #>(L035B)
	bra     L042B
L0356:	lda     #$82
	jsr     pusha0
	lda     #$3C
	jsr     pusha0
	lda     #<(L0361)
	ldx     #>(L0361)
L042B:	jsr     pushax
	jsr     _textxy
	lda     (sp)
	pha
	ina
	sta     (sp)
	pla
	and     #$20
	beq     L0363
	lda     #$05
	jsr     pusha0
	lda     #$5D
	jsr     pusha0
	lda     #<(L0368)
	ldx     #>(L0368)
	jsr     pushax
	jsr     _textxy
L0363:	lda     #$04
	jsr     pusha
	ldx     #$00
	lda     #$01
	jsr     _tgi_ioctl
L036F:	lda     #$04
	jsr     pusha
	ldx     #$00
	txa
	jsr     _tgi_ioctl
	stx     tmp1
	ora     tmp1
	bne     L036F
	lda     #<(_menubg1_pal)
	ldx     #>(_menubg1_pal)
	jsr     _tgi_setpalette
	jsr     _checkInput
	ldy     #$02
	sta     (sp),y
	lda     _joy_masks+4
	and     (sp),y
	pha
	pla
	jeq     L0377
	dey
	lda     (sp),y
	jne     L0377
	ldy     #$04
	lda     (sp),y
	bne     L041D
	lda     _altview
	jsr     bnega
	sta     _altview
	bra     L039A
L041D:	lda     (sp),y
	cmp     #$01
	bne     L041F
	lda     _lastmove
	jsr     bnega
	sta     _lastmove
	bra     L039A
L041F:	lda     (sp),y
	cmp     #$02
	bne     L0421
	lda     _musicEnabled
	jsr     bnega
	sta     _musicEnabled
	lda     _musicEnabled
	beq     L038C
	lda     #$00
	jsr     pusha
	lda     _musicptr
	ldx     _musicptr+1
	jsr     _lynx_snd_play
	lda     #$01
	jsr     pusha
	lda     _musicptr+2
	ldx     _musicptr+2+1
	jsr     _lynx_snd_play
	lda     #$02
	jsr     pusha
	lda     _musicptr+4
	ldx     _musicptr+4+1
	jsr     _lynx_snd_play
	bra     L039A
L038C:	tay
	jsr     _lynx_snd_stop
	bra     L039A
L0421:	lda     (sp),y
	cmp     #$03
	bne     L039A
	lda     #$01
	dey
	sta     (sp),y
L039A:	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
L0377:	lda     _joy_masks
	ldy     #$02
	and     (sp),y
	pha
	pla
	beq     L03A2
	dey
	lda     (sp),y
	bne     L03A2
	ldy     #$04
	lda     (sp),y
	clc
	adc     #$03
	and     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
L03A2:	lda     _joy_masks+1
	ldy     #$02
	and     (sp),y
	pha
	pla
	beq     L042C
	dey
	lda     (sp),y
	bne     L03B0
	ldy     #$04
	lda     (sp),y
	ina
	and     #$03
	sta     (sp),y
	lda     #<(_SAMPLE2_FILENR)
	ldx     #>(_SAMPLE2_FILENR)
	jsr     pushax
	jsr     _play_PCM
	lda     #$01
	tay
	sta     (sp),y
L03B0:	iny
L042C:	lda     (sp),y
	bne     L0316
	dey
	sta     (sp),y
L0316:	ldy     #$03
	lda     (sp),y
	bne     L0415
	lda     _reset
	jeq     L0314
	jmp     incsp5
L0415:	jmp     incsp5

.endproc

