;
; File generated by cc65 v 2.13.9
;
	.fopt		compiler,"cc65 v 2.13.9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_ser_get
	.import		_ser_put
	.export		_netClearBuffer
	.export		_netClose
	.export		_netSendData
	.export		_netReceiveData
	.export		_netListen
	.export		_netConnect

; ---------------------------------------------------------------
; void __near__ netClearBuffer (void)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netClearBuffer: near

.segment	"GAME2P_CODE"

	jsr     decsp1
L0004:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	beq     L0004
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ netClose (void)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netClose: near

.segment	"GAME2P_CODE"

	jmp     _netClearBuffer

.endproc

; ---------------------------------------------------------------
; void __near__ netSendData (__near__ unsigned char*, unsigned char)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netSendData: near

.segment	"GAME2P_CODE"

	jsr     decsp2
	lda     #$00
	ldy     #$01
L0069:	sta     (sp),y
	iny
	cmp     (sp),y
	bcs     L001F
L0014:	ldy     #$04
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (sp),y
	tay
	lda     (ptr1),y
	jsr     _ser_put
	tax
	bne     L0014
L001A:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L001A
	ldy     #$01
	lda     (sp),y
	ina
	bra     L0069
L001F:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L001F
	lda     (sp)
	cmp     #$FF
	bne     L001F
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ netReceiveData (__near__ unsigned char*, unsigned char)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netReceiveData: near

.segment	"GAME2P_CODE"

	lda     #$00
	jsr     pusha
	jsr     decsp1
	bra     L0027
L002B:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L002B
	ldy     #$06
	jsr     pushwysp
	ldy     #$03
	lda     (sp),y
	pha
	ina
	sta     (sp),y
	pla
	jsr     tosadda0
	sta     ptr1
	stx     ptr1+1
	lda     (sp)
	sta     (ptr1)
L0027:	ldy     #$01
	lda     (sp),y
	iny
	cmp     (sp),y
	bcc     L002B
L0033:	lda     #$FF
	jsr     _ser_put
	cmp     #$00
	bne     L0033
L0038:	lda     #$01
	jsr     leaa0sp
	jsr     _ser_get
	cmp     #$00
	bne     L0038
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ netListen (void)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netListen: near

.segment	"GAME2P_CODE"

	lda     #$FF
	jsr     pusha
	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L0043
	tax
	lda     (sp)
	cmp     #$01
	bne     L006A
	jmp     incsp1
L0043:	ldx     #$00
L006A:	txa
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ netConnect (void)
; ---------------------------------------------------------------

.segment	"GAME2P_CODE"

.proc	_netConnect: near

.segment	"GAME2P_CODE"

	lda     #$FF
	jsr     pusha
	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L005C
	tax
	lda     (sp)
	bne     L006C
L004F:	lda     #$01
	jsr     _ser_put
	cmp     #$00
	bne     L004F
L0054:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L0054
	tax
	ina
	jmp     incsp1
L005C:	lda     #$00
	jsr     _ser_put
	cmp     #$00
	bne     L005C
L0061:	lda     sp
	ldx     sp+1
	jsr     _ser_get
	cmp     #$00
	bne     L0061
	tax
L006C:	txa
	jmp     incsp1

.endproc

